### ISSUE TITLE
Issue writing in med format

### ISSUE THREAD

**Issue by valedy** [nschloe/meshio#967] opened 2020-11-12 11:19 UTC
Hello, 
I'm working with the python module. I've created a 3d surface mesh in meshio format and I would like to write it in MED format. 
An extract of my code is bellow, where file_name = /path/to/folder/surface.med:
#################################
            # create meshio mesh
            mio_surface = mio_tools.create_meshio_mesh(
                                            pt_coords=self.surface_pt_coords,
                                            connectivity=self.surface_conn,
                                            offsets=self.surface_off,
                                            cell_types=self.surface_cell_types)
            # Initialize pressure field
            data = list()
            for i in range(len(self.surface_cell_types)):
                data.append(1)
            pressure_data = np.array(data)
            mio_surface.cell_data["pressure"] = pressure_data
            # Write surface mesh on disk
            file_name = self.aster_working_dir + self.surface_med_file_name
            meshio.write(filename=file_name, mesh=mio_surface, file_format="med")
###########################################"

Here is the content of mio_tools : 
##############################
import meshio
import numpy as np

vtk_to_meshio_types = {
    5: "triangle",
    9: "quad",
    10: "tetra",
    12: "hexahedron"
}

vtktypes_to_nb_of_pts = {
    5: 3,
    9: 4,
    10: 4,
    12: 8
}

def create_meshio_mesh(pt_coords, connectivity, offsets, cell_types):
    # points
    mio_points=np.array([np.array(c) for c in pt_coords])
    # cells
    mio_cells = list()
    for i in range(len(cell_types)):
        nb_of_pts = vtktypes_to_nb_of_pts[cell_types[i]]
        pid_list = list()
        for j in range(nb_of_pts):
            pos = int(offsets[i] + j)
            pid_list.append(int(connectivity[pos]))
        mio_cells.append((vtk_to_meshio_types[int(cell_types[i])], np.array([pid_list])))
    mio_mesh = meshio.Mesh(points=mio_points, cells=mio_cells)
    return mio_mesh
###############################

To test it, one could use these datas : 
#################################
pt_coords = [ [0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0] ]
connectivity = [0, 1, 2, 3, 1, 2]
offsets = [0,3,6]
cell_types =[5,5]
##################################

I'm being very confused because if I change the file extension and the file_format to "vtk" the mesh is written correctly. But with "med" format the written mesh as the points but only 1 cell. Does someone have any hints? 
Thanks in advance, 
V.

**Comment by nschloe** [comment] 2020-11-12 11:22
Duplicate of https://github.com/nschloe/meshio/issues/965. Please simply reopen that. Also, learn GitHub markdown before posting. It's says it right there in the template.

**Closed by nschloe** 2020-11-12 11:22 UTC
