### ISSUE TITLE
Missing space after OFF breaks .off reader

### ISSUE THREAD

**Issue by lucmos** [nschloe/meshio#1035] opened 2021-02-24 10:38 UTC
# Bug

Some `.off` meshes sometimes miss the newline after the OFF header. `meshio.read` does not gently handle such errors.

# Example

e.g. in the dataset ModelNet40, [`train/sofa_0001.off.zip`](https://github.com/nschloe/meshio/files/6035263/sofa_0001.off.zip)

```
OFF26462 27438 0
-20.976212 -25.048400 -4.046448
-21.020429 -21.895600 -5.326308
-20.976212 -25.048400 -5.326308
-20.843563 -26.750800 -5.326308
-21.020429 -21.895600 -4.046448
-20.976212 -25.048400 -6.695388
-20.843563 -26.750800 -4.046448
-21.020429 -21.895600 -2.997248
-21.020429 -16.730400 -4.046448
-21.020429 -21.895600 -6.695388
...
```

Reading this file raises an error
![image](https://user-images.githubusercontent.com/11019190/108987460-9bbc2180-7693-11eb-8864-b04280c61f9b.png)

# Additional context

My current workaround to this problem is to create a temporary file in which I add a newline, if it is missing.

I'm working on a PR for pytorch geometric to integrate meshio (related issue https://github.com/rusty1s/pytorch_geometric/issues/2151). 
ModelNet40 is integrated in pytorch geometric, thus it is certain to occur often

# Proposed Solution

Would it be possible to increase the robustness of the `off` reader to handle a missing space after `OFF`?

**Comment by nschloe** [comment] 2021-02-24 13:22
I'm not sure about this one. The issue is clearly with the file, and meshio _does_ handle it gently by throwing an error with a clear error message. I suppose the software that produces the file should be fixed, right?

**Comment by lucmos** [comment] 2021-02-24 14:10
I completely agree with you! The problem is in the dataset, and `meshio` does everything correctly.

My points are:
- [ModelNet](https://modelnet.cs.princeton.edu/) and possibly other datasets, which I am not aware of, are broken in this way. If I want to read this dataset, I have to: (1) manually fix all the broken `.off` files, or (2) do not use `meshio`. 
- The integration of `meshio` in PyTorch Geometric cannot happen if `meshio` does not handle these broken files. Since ModelNet is integrated into PyTorch Geometric, problems arise if `meshio` cannot handle such files.

I'm sorry If the bug report came across the wrong way, my request is not to "fix" meshio but to make it more resilient to broken mesh files that occur in practice.

**Comment by nschloe** [comment] 2021-02-24 14:46
> I'm sorry If the bug report came across the wrong way, 

Don't worry, I understand.

> ModelNet and possibly other datasets, which I am not aware of, are broken in this way.

Why don't report to ModelNet? Shuran Song appears to be in charge.

The page seems to be broken in more than one way; with a recent version of Chrome, the download fails with

> Mixed Content: The page at 'https://modelnet.cs.princeton.edu/#' was loaded over HTTPS, but requested an insecure resource 'http://3dvision.princeton.edu/projects/2014/3DShapeNets/ModelNet10.zip'. This request has been blocked; the content must be served over HTTPS.

**Comment by nschloe** [comment] 2021-02-24 14:51
This is a bit of a philosophical question here. By accepting broken meshes in meshio, we soften up the standard (which is bad for everyone) and make our own code (which we have have to maintain) more complicated. In fact, the reason that Shuran didn't notice that the dataset is broken is probably because of a too lenient reader somewhere. This is why I'm pushing a little against this.

**Comment by nschloe** [comment] 2021-06-06 13:50
I thought about it some more and still find the missing newline to grave of a violation of the standard. In general, though, we could be more lenient in meshio and emit warnings on standard violations.

**Closed by nschloe** 2021-06-06 13:50 UTC
