### ISSUE TITLE
Cannot read binary STL file with a header that starts with "solid"

### ISSUE THREAD

**Issue by s1291** [nschloe/meshio#530] opened 2019-11-22 14:32 UTC
According to [wikipedia](https://en.wikipedia.org/wiki/STL_(file_format)#Binary_STL), binary STL files should never begin with "solid" because that may lead some software to assume that this is an ASCII STL file.
However, a lot of binary files start with `solid` (E.g. Binary stl files from SolidWorks, ..etc). Those files could be read by many software (Paraview, Blender, meshlab, ...etc).

Currently, meshio couldn't read these binary files.

Here is an example of two binary stl files (with and without header):
* [cube-header.zip](https://github.com/nschloe/meshio/files/3879908/cube-header.zip)
* [cube-without-header.zip](https://github.com/nschloe/meshio/files/3879913/cube-without-header.zip)

To solve the issue, the `_read_binary` function should look like:
```
...
  with open(filename, mode) as fh:
            header = fh.read(80)
            size, = struct.unpack('@i', fh.read(4))
            data = numpy.fromfile(fh, dtype=cls.dtype, count=size)
...
```

And the function `read_buffer` must be fixed to detect the type of the stl file (ascii or binary)

PS: [numpy-stl](https://github.com/WoLpH/numpy-stl/) could read both types of binary stl files(i,e: with and without header)

**Comment by s1291** [comment] 2019-11-22 15:00
The issue is with `read_buffer` function.

**Comment by nschloe** [comment] 2019-11-22 18:13
> And the function read_buffer must be fixed to detect the type of the stl file (ascii or binary)

Any idea how?

**Comment by s1291** [comment] 2019-11-22 18:18
This is discussed here:
* [Verifying that an STL file is ASCII or binary](https://stackoverflow.com/questions/7377954/how-to-detect-that-this-is-a-valid-valid-binary-stlstereolithography-file).

**Comment by nschloe** [comment] 2019-11-24 20:56
Thanks for the links. The issue is fixed now and will be part of the next release.

**Closed** 2019-11-24 20:55 UTC
