### ISSUE TITLE
meshio takes up a huge amount of RAM

### ISSUE THREAD

**Issue by massimiliano-leoni** [nschloe/meshio#154] opened 2017-11-30 17:38 UTC
For example, to convert a 283.3MB msh file into a 520.3MB xml file the peak RAM allocated was 9.8GB. Is this normal? Can it be optimized?

**Comment by nschloe** [comment] 2017-11-30 18:20
An interesting problem. What file formats are you converting from and to?

**Comment by massimiliano-leoni** [comment] 2017-11-30 18:24
Gmsh msh to dolfin XML

**Comment by nschloe** [comment] 2017-11-30 18:43
Well, first of all let me say that dolfin XML is a legacy format. FEniCS only uses XDMF upstream now. I should probably add a warning here.

I'm still very interested in ironing out the memory disaster here of course. First, let's find out if it's the reader or the writer that's causing trouble. Could you run the Python program
```python
import meshio
meshio.read('foo.msh')
```
and let me know if the issue is there? (Alternatively, you could upload your mesh somewhere so I can play around with it myself.)

**Comment by massimiliano-leoni** [comment] 2017-12-01 10:12
I know, we've had this discussion already. I work with fenics-hpc and unfortunately I need to pass through dolfin xml.

I run your snippet but reading in the xml mesh and RAM usage skyrocketed to 8.9GB, so I think the issue is with the xml reader. I cannot give you the exact same mesh I'm using, but I've seen this problem with every "big" mesh converted to xml, so I can produce a good example of a random geometry and try to share that with you.

**Comment by nschloe** [comment] 2017-12-01 10:20
fenics-_hpc_ uses XML meshes? Oh my...

I'll be waiting for the mesh.

**Comment by massimiliano-leoni** [comment] 2017-12-01 14:27
Actually no, we have another format which is more efficient, but to convert to that format I have to convert to xml first. I put a big mesh in my google drive, you can get it from https://drive.google.com/open?id=1njA0C3JzEfIZ64vElk0NfjOlMunMzO3p . When read with the snippet you wrote above it takes more than 8GB of RAM to load.

**Comment by nschloe** [comment] 2017-12-20 11:10
Yep, I see the same behavior. Unfortunately, this is a hassle to debug. Do you have a mesh that blows up only to a few hundred MB when converting?

**Comment by massimiliano-leoni** [comment] 2017-12-20 11:58
I am trying to convert to dolfin-xml with the latest meshio for Python2 but I get the following error:

```
Number of points: 18417
Elements:
  Number of tetras: 81062
  Number of lines: 236
  Number of triangles: 17788
Cell data: geometrical, physical
WARNING:root:Dolfin's XML is a legacy format. Consider using XDMF instead.
WARNING:root:DOLFIN XML can only handle one cell type at a time. Using tetra, discarding line, triangle.
Traceback (most recent call last):
  File "/home/mleoni/.local/bin/meshio-convert", line 135, in <module>
    _main()
  File "/home/mleoni/.local/bin/meshio-convert", line 75, in _main
    field_data=field_data
  File "/home/mleoni/.local/lib/python2.7/site-packages/meshio/helpers.py", line 178, in write
    dolfin_io.write(filename, points, cells, cell_data=cell_data)
  File "/home/mleoni/.local/lib/python2.7/site-packages/meshio/dolfin_io.py", line 251, in write
    _write_mesh(filename, points, cell_type, cells)
  File "/home/mleoni/.local/lib/python2.7/site-packages/meshio/dolfin_io.py", line 185, in _write_mesh
    tree.write(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize {'dolfin': 'https://fenicsproject.org/'} (type dict)

```

I could convert with the old `dolfin-convert`, the resulting mesh is here https://drive.google.com/open?id=1ruIs5N2gExnS0tuKodZj6sqEyRZCSUO_
When read with meshio, memory goes up to 500MB and then stabilized at 200MB, for a 10MB mesh file.

**Comment by nschloe** [comment] 2017-12-20 14:37
Should be fixed now. Get 1.10.7 and try it out.

**Closed** 2017-12-20 14:36 UTC

**Comment by massimiliano-leoni** [comment] 2017-12-20 14:52
I'm getting this

```
~$ ipython3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import meshio

In [2]: meshio.read("Mesh_1.xml")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-0651de1989cd> in <module>()
----> 1 meshio.read("Mesh_1.xml")

/home/mleoni/.local/lib/python3.5/site-packages/meshio/helpers.py in read(filename, file_format)
    119         }
    120 
--> 121     return format_to_reader[file_format].read(filename)
    122 
    123 

/home/mleoni/.local/lib/python3.5/site-packages/meshio/dolfin_io.py in read(filename)
    105 
    106 def read(filename):
--> 107     points, cells, cell_type = _read_mesh(filename)
    108     point_data = {}
    109     cell_data = _read_cell_data(filename, cell_type)

/home/mleoni/.local/lib/python3.5/site-packages/meshio/dolfin_io.py in _read_mesh(filename)
     29 
     30         if elem.tag == 'dolfin':
---> 31             assert elem.attrib['nsmap'] \
     32                 == '{\'dolfin\': \'https://fenicsproject.org/\'}'
     33         elif elem.tag == 'mesh':

KeyError: 'nsmap'
```

**Comment by nschloe** [comment] 2017-12-20 15:48
Well what does your file look like at that position?

**Comment by massimiliano-leoni** [comment] 2017-12-20 16:03
This file, the first one I shared, starts with `<dolfin xmlns:dolfin="http://fenicsproject.org/">` whereas another one that I just generated with meshio converting from vtu to dolfin-xml starts with `<dolfin nsmap="{'dolfin': 'https://fenicsproject.org/'}">`, so I guess the problem here is that the first header is not recognized.

Also, I tried just now to convert a mesh from gmsh-msh to dolfin-xml and got
```
Traceback (most recent call last):                                                                                                   
  File "/home/mleoni/.local/bin/meshio-convert", line 135, in <module>                                                               
    _main()                                                                                                                          
  File "/home/mleoni/.local/bin/meshio-convert", line 18, in _main                                                                   
    meshio.read(args.infile, file_format=args.input_format)                                                                          
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/helpers.py", line 121, in read                                        
    return format_to_reader[file_format].read(filename)
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 99, in read
    out = read_buffer(f)
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 364, in read_buffer
    f, 'ElementData', cell_data_raw, int_size, data_size, is_ascii
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 274, in _read_data
    num_string_tags = int(f.readline().decode('utf-8'))
ValueError: invalid literal for int() with base 10: ''

```

**Comment by massimiliano-leoni** [comment] 2017-12-20 16:26
Also, the xml file generated by meshio has no linebreaks, the whole xml is on a single line.

**Comment by nschloe** [comment] 2017-12-20 17:19
Could you simply remove the assertion to see if it works for you from there on out?

> Also, the xml file generated by meshio has no linebreaks, the whole xml is on a single line.

Yeah that's intended, adding line breaks is more expensive computationally. VTU has that done similarly https://github.com/nschloe/meshio/blob/master/meshio/vtu_io.py#L404. Is pretty printing a requirement for you?

> Also, I tried just now to convert a mesh from gmsh-msh to dolfin-xml and got

That's a different issue. Could you open a new issue and append the mesh?

**Comment by massimiliano-leoni** [comment] 2017-12-21 09:31
Removing the assertion works, I get the mesh converted correctly. I did again the reading test and now it only took 611MB to read a 462MB mesh, stabilizing at 230MB after the read operation was completed. I think this is much better than before, and indeed fixes my issue. Thanks!

Pretty printing is not a requirement, actually I couldn't care less. If omitting line breaks is cheaper, then so be it!

I will open a new issue for the gmsh reader now.

**Comment by massimiliano-leoni** [comment] 2017-12-21 09:32
[So what do we do with the assert? Can you take care of that?]

**Comment by nschloe** [comment] 2017-12-21 11:15
Yep, I'll take care of it. Just wanted to make sure that it then works for you at least for now.
