### ISSUE TITLE
Fluent .msh: support binary, and elements -> faces -> nodes mapping

### ISSUE THREAD

**Issue by certik** [nschloe/meshio#90] opened 2017-05-12 16:14 UTC
Unfortunately I can't share the whole Fluent .msh file, but I can share the beginning at least:
```
(0 machine configuration:)
(4 (60 0 0 1 2 4 4 4 8 4 8))
(0 grid written by ANSYS Meshing
   nodes:       (10 (id start end type) (x y z ...))
              faces:       (13 (id start end type elemType)
                (v-0 v-1 .. v-n right-cell left-cell ...))
   cells:       (12 (id start end type elemtype))
   parent-face: (59 (start end parent child) (nchilds child0 child1 ...))
)
(2 3)
(10 (0 1 5406dd 0))
(13 (0 1 2202aa7 0))
(12 (0 1 ece71a 0))
(3010 (3 1 430529 1 3)
(<9b>ĎDŘHřČ?5QÁ^K.SÚżBÉEÔe<82>Ĺżü VęGŢČ?Qn^Yum_Úż6Ś<8f>^]Ţ<9c>Ĺż\<81>Ú˘b]É?^[D<88>x.^^ÚżÜç<80>T<8a>^DĹż^_Oţă/$É?x=ůŐ<9a>3ÚżšłßB^DKĹżtň#rÎ^RÉ?
```
There are two issues:

* it uses a binary format (that's easy to fix, one just has to read it properly and convert)
* it doesn't save elements -> nodes mapping, but rather elements -> faces -> nodes mapping, which makes it actually quite technical to convert into the usual elements -> nodes mapping, so that one can convert to other formats.

**Comment by nschloe** [comment] 2017-05-12 16:23
The binary thing should be solvable, I agree. I'm wondering about the `3010` index in the file -- what does that mean? I [the format documentation](https://www.sharcnet.ca/Software/TGrid/pdf/ug/appb.pdf) I only see `1`, `10`, `12` etc.

**Comment by certik** [comment] 2017-05-12 16:49
I don't remember at the moment, but I am sure that we can figure out.

The hard part is the element->face->node conversion. I am attaching my script that I wrote, but if I remember well, it's not perfect, there are still some corner cases to fix: https://gist.github.com/certik/1f17148f71a85546afbf20ac39778568

It reads the fluent mesh and converts into ExodusII. It'd be nice to integrate with your library.

If you give me your gitlab.com ID, I can add you to my private project where I have a set of about 20 Fluent meshes that you can test the reader on.

**Comment by certik** [comment] 2017-05-12 16:51
P.S. the 3010 is a start of double precision binary data, see http://www.afs.enea.it/fluent/Public/Fluent-Doc/PDF/chp03.pdf, section 3.18.1.

**Comment by nschloe** [comment] 2017-05-17 09:07
In the meantime, multiple improvements for ANSYS i/o landed in meshio. I still don't have an example file with binary data or the above mapping at hand. @certik Could you help out?

**Comment by certik** [comment] 2017-05-17 14:32
@nschloe thanks a lot for improving the reader. I can't share the file that I have (and that I needed to convert), but I'll try to find some file with binary data, as well as the faces instead of nodes, that I can share -- if I find it, I'll post here.

**Comment by certik** [comment] 2017-05-17 14:38
Ah, that was easy, here I found 4 files with binary data:

http://www.ewp.rpi.edu/hartford/~zelezl/Master%27s%20Project/Other/Final%20Working%20Files/ANSYS%20Files/Final%20Gaussian%20Constriction%20Cases_files/dp0/FFF-13/MECH/FFF-13.msh

http://www.ewp.rpi.edu/hartford/~wallj2/CFD/HW3/Hw3_2_files/DP0/SYS/MECH/SYS.MSH

https://www.researchgate.net/file.PostFileLoader.html?id=5559c00461432533428b45db&assetKey=AS%3A273779018665996%401442285412410

http://edge.rit.edu/edge/P15441/public/Detailed%20Design%20Documents/ANSYS%20%26%20ANSYS%20Models/Fluent%20Analysis_files/dp0/FFF-2/MECH/FFF-2.1.msh

**Comment by certik** [comment] 2017-05-17 14:44
Btw, according to this, large portions of the reader are not tested:

https://codecov.io/gh/nschloe/meshio/src/master/meshio/ansys_io.py

**Comment by nschloe** [comment] 2017-05-17 15:02
Thanks Ondrej for the links.

> Btw, according to this, large portions of the reader are not tested:

You're right. The total coverage is 85% right now, which is okay but not great. As you already noticed, the testing works such that a mesh is generated, then written, read, and the result is tested with the initial mesh. This is repeated for a bunch of different meshes (triangles, tets, quads etc.). What this doesn't test is, e.g., ANSYS's notion of faces (index `13` in files) and oddities like empty lines here and there. I'm going to have to come back to this.

**Comment by nschloe** [comment] 2017-05-18 17:46
Binary data should work now. I've tested it will all the files you posted.

**Comment by nschloe** [comment] 2017-06-14 14:08
There's nothing I can do at this point, so let me close this bug. Feel free to reopen at any time.

**Closed by nschloe** 2017-06-14 14:08 UTC

**Comment by certik** [comment] 2017-06-14 15:14
@nschloe thanks a lot for implementing it. I just installed the newest version of meshio, and here is what I got:
```
$ meshio-convert --input-format ansys my_mesh.msh output.exo
Traceback (most recent call last):
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not unicode
Logged from file ansys_io.py, line 354
Traceback (most recent call last):
  File "/home/certik/ext/miniconda2/envs/meshio/bin/meshio-convert", line 4, in <module>
    __import__('pkg_resources').run_script('meshio==1.8.9', 'meshio-convert')
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/site-packages/meshio-1.8.9-py2.7.egg/EGG-INFO/scripts/meshio-convert", line 130, in <module>
    
  File "/home/certik/ext/miniconda2/envs/meshio/lib/python2.7/site-packages/meshio-1.8.9-py2.7.egg/EGG-INFO/scripts/meshio-convert", line 16, in _main
    
  File "build/bdist.linux-x86_64/egg/meshio/helpers.py", line 91, in read
  File "build/bdist.linux-x86_64/egg/meshio/ansys_io.py", line 345, in read
  File "build/bdist.linux-x86_64/egg/meshio/ansys_io.py", line 264, in _read_faces
AssertionError
```

**Comment by nschloe** [comment] 2017-06-14 15:26
@certik Do you have a mesh with which I can reproduce the error?

**Comment by certik** [comment] 2017-06-14 15:31
@nschloe Unfortunately I can't distribute this mesh.

It's fine. If I need this again in the future, I will try to get a hold of the software and generate some smaller meshes and open source them. Right now I don't have access to the software that generates them.

**Comment by nschloe** [comment] 2017-06-14 15:33
Alright, sounds good. I'll be happy to look at it again then.

**Comment by falgunithakor-hunterindustries** [comment] 2019-05-13 22:36
Hello Nico Schlömer, 

I am trying to use Meshio for reading and writing Ansys .msh binary files. As per the above conversation, it looks like it should be simply able to call `meshio.read('mesh001.msh')` where mesh001.msh is Ansys generated binary mesh file. 

Although, I am getting below error:
`Traceback (most recent call last):
  File "data/Example.py", line 29, in <module>
    mesh3 = meshio.read('mesh001.msh')
  File "Python37\lib\site-packages\meshio\helpers.py", line 174, in read
    return format_to_reader[file_format].read(filename)
  File "Python37\lib\site-packages\meshio\msh_io\main.py", line 14, in read
    mesh = read_buffer(f)
  File "Python37\lib\site-packages\meshio\msh_io\main.py", line 30, in read_buffer
    assert line == "$MeshFormat"
AssertionError`

I received the same error when I tried msh file from https://www.researchgate.net/file.PostFileLoader.html?id=5559c00461432533428b45db&assetKey=AS%3A273779018665996%401442285412410 (Ansys generated non-binary mesh file)

Please suggest!

**Comment by keurfonluu** [comment] 2019-05-13 22:41
Not an error, msh format is associated to Gmsh files in meshio. For Ansys msh files, you may refer to issue https://github.com/nschloe/meshio/issues/373

**Comment by falgunithakor-hunterindustries** [comment] 2019-05-13 22:56
@keurfonluu Thanks for pointing that out. 
 meshio.read("mesh001.msh", file_format = 'ansys-binary') worked perfectly fine.

@nschloe Do you think I can do a pull request on README file to add indicate the usage of file_format?

**Comment by nschloe** [comment] 2019-05-15 18:14
@falgunithakor-hunterindustries Done.
