### ISSUE TITLE
reading in vtu from Firedrake

### ISSUE THREAD

**Issue by krober10nd** [nschloe/meshio#1019] opened 2021-02-14 20:56 UTC
* I have a vtu file that I created using P=2, KMV simplical elements from a Firedrake code of mine. I recently added these elements inside FIAT. 
* When I try to read this file using `meshio` I get.
```python
import meshio
mesh = meshio.read('control_40.vtu')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshio/_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 506, in read
    reader = VtuReader(filename)
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 386, in __init__
    point_offsets, cells, cell_data_raw
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 110, in _organize_cells
    cdr,
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 86, in _cells_from_data
    n = num_nodes_per_cell[meshio_type]
KeyError: 'VTK_LAGRANGE_TRIANGLE'
```
[control_40.vtu.zip](https://github.com/nschloe/meshio/files/5978498/control_40.vtu.zip)

In ParaView, the file appears fine. 

Any idea what could be wrong here? 

Thanks

**Comment by nschloe** [comment] 2021-02-15 10:58
Duplicate of https://github.com/nschloe/meshio/issues/1003.

**Closed by nschloe** 2021-02-15 10:58 UTC

**Comment by krober10nd** [comment] 2021-02-15 12:33
thanks! updated `meshio` and it works now.
