### ISSUE TITLE
Use XDMF output with ASCII only

### ISSUE THREAD

**Issue by chrisrichardson** [nschloe/meshio#76] opened 2017-03-24 15:23 UTC
I just tried to output to xdmf, but got:
```
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140140583401216:
  #000: ../../../src/H5T.c line 1671 in H5Tcopy(): not a datatype or dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
XDMF Error in /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfDataDesc.cxx line 492 (Error Creating Data Type)
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140140583401216:
  #000: ../../../src/H5T.c line 1671 in H5Tcopy(): not a datatype or dataset
    major: Invalid arguments to routine
```

and a lot more error messages - is it possible to switch to ASCII only XDMF (i.e. pure XML). Although it may be less efficient in storage, it is less likely to cause a crash from conflicting library versions etc.

**Comment by nschloe** [comment] 2017-03-24 17:47
meshio uses [vtkXdmfWriter](http://www.vtk.org/doc/nightly/html/classvtkXdmfWriter.html) under the hood, and as far I can see, there's no such option.

I was going to suggest to add a XDMF3 output, but that's only in VTK 6.2.0 which isn't included in Ubuntu Trusty, meshio's testing platform (via travis). I've started [a backports PPA](https://launchpad.net/~nschloe/+archive/ubuntu/vtk-backp), but that wasn't successful yet. Do you know of a VTK 6.2+ PPA for trusty?

**Comment by nschloe** [comment] 2017-03-24 17:56
Wait, we're skipping VTK in all tests anyways. Let me try to add XDMF3.

**Comment by nschloe** [comment] 2017-03-24 18:04
Yikes.
```
AttributeError: 'module' object has no attribute 'vtkXdmf3Writer'
```
(With VTK 6.3.0.)

**Comment by nschloe** [comment] 2017-05-10 11:25
I've discovered a similar error when writing XDMF2 files with VTK; see [here](https://gitlab.kitware.com/vtk/vtk/issues/17039). While not necessarily related, this goes to show that VTK's XDMF2 writer isn't too reliable.

**Comment by nschloe** [comment] 2017-05-10 12:34
Alright, I could reproduce the exact error. The issue is connected to `int` arrays in VTK with XDMF2; [here](https://gitlab.kitware.com/vtk/vtk/issues/17040) is the bug report. Unfortunately, XDMF3 doesn't solve the issue; it rather skips the array (bug report [here](https://gitlab.kitware.com/vtk/vtk/issues/17041)).

Perhaps if you +1 the issues, they'll attract more attention and get fixed sooner.

**Comment by nschloe** [comment] 2017-05-12 11:38
Since this is an upstream issue, let me close this.

**Closed by nschloe** 2017-05-12 11:38 UTC
