### ISSUE TITLE
read ply point cloud error

### ISSUE THREAD

**Issue by bo-wu** [nschloe/meshio#541] opened 2019-11-28 06:11 UTC
I have a point cloud in PLY format (attached). I want to read it but got error as below. But if I convert the PLY file to OBJ, then read it successfully.  
[front.zip](https://github.com/nschloe/meshio/files/3900129/front.zip)

```
Traceback (most recent call last):
  File "mesh2pcd.py", line 27, in <module>
    main('./front.ply')
  File "mesh2pcd.py", line 21, in main
    mesh = meshio.read(mesh_name)
  File "/home/test/.local/lib/python3.7/site-packages/meshio/_helpers.py", line 214, in read
    return format_to_reader[file_format].read(filename)
  File "/home/test/.local/lib/python3.7/site-packages/meshio/_ply.py", line 33, in read
    mesh = read_buffer(f)
  File "/home/test/.local/lib/python3.7/site-packages/meshio/_ply.py", line 102, in read_buffer
    cell_dtypes,
  File "/home/test/.local/lib/python3.7/site-packages/meshio/_ply.py", line 240, in _read_binary
    for dtypes in cell_dtypes
  File "/home/test/.local/lib/python3.7/site-packages/meshio/_ply.py", line 240, in <listcomp>
    for dtypes in cell_dtypes
KeyError: 'int'
```
Currently I have no time to dig it out and just post an issue

**Comment by nschloe** [comment] 2019-11-28 09:52
Thanks for the report! The issue is fixed now and will be part of the next release.

**Closed** 2019-11-28 09:51 UTC
