### ISSUE TITLE
Convert physical entities for Exodus files (Cubit)

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [nschloe/meshio#1031] opened 2021-02-22 11:03 UTC
Hi all

I'd like to start using Coreform Cubit in a FEniCS workflow. I have been able to convert the mesh from Exodus to XDMF using meshio-convert, however the physical entities (blocks, sidesets) are not converted (ie. cell_data is empty).

```python
import meshio
  
mesh = meshio.read("my_mesh.e")
print(mesh)
```
yields:
```
<meshio mesh object>
  Number of points: 289
  Number of cells:
    triangle: 512
```

I would expect some cell_data here. Do you guys know what I'm doing wrong ?

![image](https://user-images.githubusercontent.com/40028739/108699768-f889d180-7505-11eb-920b-b0ffc653518b.png)

[files.zip](https://github.com/nschloe/meshio/files/6021471/files.zip)

**Comment by nschloe** [comment] 2021-03-09 14:18
Duplicate of https://github.com/nschloe/meshio/issues/729.

**Closed by nschloe** 2021-03-09 14:18 UTC

**Comment by RemDelaporteMathurin** [comment] 2024-02-23 00:14
> Duplicate of #729.

Hi @nschloe , I'm looking back at this years later. Do you know if there's now a way to tag subdomains of a mesh in Cubit, export it, and convert it using meshio?

**Comment by nschloe** [comment] 2024-02-23 00:15
None that I know of.
