### ISSUE TITLE
[REQUEST] Support exodus time series

### ISSUE THREAD

**Issue by j-bowhay** [nschloe/meshio#1328] opened 2022-06-07 15:12 UTC
**How would you improve meshio?**

It would be nice to be able to read time series exodus files. I was interested in this comment
https://github.com/nschloe/meshio/blob/0138cc8692b806b44b32d344f7961e8370121ff7/src/meshio/exodus/_exodus.py#L136-L139
seems to imply that it might be possible? I would be happy to try attempt this given some guidance.

**What problem does it solved for you?**

With [MOOSE](https://github.com/idaholab/moose) becoming more popular for multiphysics simulation, meshio could be a nice way to get the data into python.

**Comment by nschloe** [comment] 2022-06-07 19:51
Duplicate of #381.

**Closed as completed by nschloe** 2022-06-07 19:51 UTC
