### ISSUE TITLE
pip install in jupyter

### ISSUE THREAD

**Issue by chrisrichardson** [nschloe/meshio#74] opened 2017-03-24 12:46 UTC
I'm getting the following problem with python3 and pip install on jupyter (specifically on notebooks.azure.com):
```
!pip install meshio

Collecting meshio
  Using cached meshio-1.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-564tyt8x/meshio/setup.py", line 11, in <module>
        exec(f.read(), about)
      File "/home/nbcommon/anaconda3_410/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-564tyt8x/meshio/
```

Clearly some kind of UTF-8 issue?

**Comment by nschloe** [comment] 2017-03-24 13:32
Oh, the troubles of having an umlaut in one's name. I just uploaded a new version, does this fix your error?

**Comment by chrisrichardson** [comment] 2017-03-24 13:38
```

**Comment by nschloe** [comment] 2017-03-24 13:40
Hm, alright. Can you give me more details on how to reproduce this?

**Comment by chrisrichardson** [comment] 2017-03-24 13:41
It seems to be specific to python3. If you try `pip3 install meshio` on ubuntu, you will probably get it.

**Comment by nschloe** [comment] 2017-03-24 13:49
python3, now that's funny.

Anyways, I cannot reproduce:
```
$ pip3 install meshio
Collecting meshio
  Using cached meshio-1.7.5.tar.gz
Collecting numpy (from meshio)
  Downloading numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 100kB/s 
Collecting pipdated (from meshio)
  Downloading pipdated-0.1.6.tar.gz
Collecting appdirs (from pipdated->meshio)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting requests (from pipdated->meshio)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 1.6MB/s 
Building wheels for collected packages: meshio, pipdated
  Running setup.py bdist_wheel for meshio ... done
  Stored in directory: /home/nschloe/.cache/pip/wheels/66/e7/d2/b654c8dc2336f1ebcbfa481417183a8738772ccb9c71c331c3
  Running setup.py bdist_wheel for pipdated ... done
  Stored in directory: /home/nschloe/.cache/pip/wheels/9f/a5/dc/c37f31afff6047e5b0a3db2ddaf2986a6f985000504d381641
Successfully built meshio pipdated
Installing collected packages: numpy, appdirs, requests, pipdated, meshio
Successfully installed appdirs-1.4.3 meshio-1.7.5 numpy-1.12.1 pipdated-0.1.6 requests-2.13.0
```

**Comment by chrisrichardson** [comment] 2017-03-24 14:01
Hmmm... I tried in a docker container `docker run -ti ubuntu:16.04`
```
apt-get update
apt-get install python3
apt-get install python3-pip
pip3 install meshio
root@89979721a718:/# pip3 install meshio
Collecting meshio
  Downloading meshio-1.7.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5oa2kmd_/meshio/setup.py", line 11, in <module>
        exec(f.read(), about)
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)
    
```

**Comment by nschloe** [comment] 2017-03-24 15:38
I now fired up a clean plain virtual box with 16.04. Still no luck in reproducing. I did
```
vagrant init ubuntu/xenial64
vagrant up
vagrant ssh
```
and in the box
```
sudo apt-get update
sudo apt-get install python3
sudo apt-get install python3-pip
pip3 install meshio
```
No problem:
```
Collecting meshio
  Downloading meshio-1.7.5.tar.gz
Collecting numpy (from meshio)
  Downloading numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 91kB/s 
Collecting pipdated (from meshio)
  Downloading pipdated-0.1.6.tar.gz
Collecting appdirs (from pipdated->meshio)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting requests (from pipdated->meshio)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 2.2MB/s 
Building wheels for collected packages: meshio, pipdated
  Running setup.py bdist_wheel for meshio ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/66/e7/d2/b654c8dc2336f1ebcbfa481417183a8738772ccb9c71c331c3
  Running setup.py bdist_wheel for pipdated ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/9f/a5/dc/c37f31afff6047e5b0a3db2ddaf2986a6f985000504d381641
Successfully built meshio pipdated
Installing collected packages: numpy, appdirs, requests, pipdated, meshio
Successfully installed appdirs meshio numpy pipdated requests-2.9.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by nschloe** [comment] 2017-03-24 15:46
Finally, success! I reproduced the error with _docker_. And as we know, a reproducible bug is a fixed bug. Well, almost...

**Comment by chrisrichardson** [comment] 2017-03-24 16:05
Maybe locale related? I haven't found much useful information from web search

**Comment by nschloe** [comment] 2017-03-24 16:10
I'm onto something in UTF-8 ocean between Python 2 and 3. We'll need a bigger boat.

**Comment by nschloe** [comment] 2017-03-24 16:43
When cloning meshio, what does
```
file meshio/__about__.py
```
say for you on docker vs. on any other machine?

**Comment by chrisrichardson** [comment] 2017-03-24 16:57
`meshio/meshio/__about__.py: UTF-8 Unicode text` everywhere I tried so far

**Comment by nschloe** [comment] 2017-03-24 17:10
I posted an MWE on stackoverflow. https://stackoverflow.com/questions/43005364/docker-unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-72

**Comment by nschloe** [comment] 2017-03-24 17:34
As a workaround, you can start docker with a sane locale,
```
docker run -e LANG=C.UTF-8 -ti ubuntu:16.04
```

**Comment by nschloe** [comment] 2017-04-14 12:02
Another way to get around this:
```
LANG=C.UTF-8 pip install meshio
```

**Comment by nschloe** [comment] 2017-04-14 12:03
Let's close this, feel free to reopen if any more problems occur.

**Closed by nschloe** 2017-04-14 12:03 UTC

**Comment by nschloe** [comment] 2017-08-15 13:24
Ghosts of the past. https://github.com/nschloe/meshio/issues/112

**Comment by nschloe** [comment] 2017-08-15 14:17
Alright, this is hopefully fixed for real now. No `LANG` settings necessary.
