### ISSUE TITLE
What happens to physical groups from pygmsh -> meshio?

### ISSUE THREAD

**Issue by tjdodwell** [nschloe/meshio#1011] opened 2021-02-10 09:49 UTC
This seems like an issue that has been raised a number of times, but I could find no solution - so sorry if I have missed something

I have constructed a basic mesh in pygmsh, with surfaces and volumes assigned physical groups.

when generating the mesh, these physical groups are losted.

I see that meshio can spit out cell data, but this is empty.

Therefore how would you manipulate pygmsh, so that meshio has physical groups in the cell_data?

**Comment by nschloe** [comment] 2021-02-10 10:40
> This seems like an issue that has been raised a number of times

Indeed, so I'll close this a duplicate of https://github.com/nschloe/meshio/issues/550.

It's best to subscribe to the relevant issues, +1 them, or even better submit a PR that fixes the issue. :)

**Closed by nschloe** 2021-02-10 10:40 UTC

**Comment by keurfonluu** [comment] 2021-02-10 19:04
> This seems like an issue that has been raised a number of times, but I could find no solution - so sorry if I have missed something
> 
> I have constructed a basic mesh in pygmsh, with surfaces and volumes assigned physical groups.
> 
> when generating the mesh, these physical groups are losted.
> 
> I see that meshio can spit out cell data, but this is empty.
> 
> Therefore how would you manipulate pygmsh, so that meshio has physical groups in the cell_data?

Do you have anything in `mesh.cell_sets`?
