### ISSUE TITLE
convert ".msh" mesh ,  ReadError(f"File {filename} not found.")

### ISSUE THREAD

**Issue by ruffi92** [nschloe/meshio#1207] opened 2021-10-31 15:14 UTC
Hi to all, probably is a trivial question but i'm not so expert and i can't find the solution. 
I have installed the last version of meshio (on macOS) and try to convert one mesh .msh into .vtk file. 
In the command line i write "meshio convert input.msh output.vtk" (the input file is on the desktop and the name is correct) but it appear the following error message:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/meshio", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_main.py", line 53, in main
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_convert.py", line 65, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_helpers.py", line 59, in read
    raise ReadError(f"File {filename} not found.")
meshio._exceptions.ReadError: File input.msh not found.

Anyone have some tips?

**Comment by gdmcbain** [comment] 2021-10-31 20:08
I think you need the full path to the file; otherwise the command looks in the current working directory, not on the desktop. This is more a shell thing than meshio.  I don't have access to macOS but this might be something like

```shell
meshio convert ~/Desktop/input.msh output.vtk
```

If the tilde doesn't work, maybe `/users/ruffi92/Desktop/input.msh` (or whatever your username is).

Or you could move input.msh into the current working directory. That might be better henceforth if this isn't a one-off.

**Comment by ruffi92** [comment] 2021-10-31 22:15
first of all thank you for the response, unfortunatly i have tried all this option but appear the same message. Where i can find the current working directory ? I try to put my mesh in : 

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio

but also this option does not work..

**Comment by gdmcbain** [comment] 2021-10-31 23:30
> Where i can find the current working directory ?

Try typing `pwd` in the shell.

**Comment by ruffi92** [comment] 2021-11-01 15:45
now seems that "see" the file but still not working correctly. The error now is: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/meshio", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_main.py", line 53, in main
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_convert.py", line 65, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_helpers.py", line 70, in read
    return reader_map[file_format](filename)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/main.py", line 19, in read
    mesh = read_buffer(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/main.py", line 34, in read_buffer
    raise ReadError()
meshio._exceptions.ReadError

mesh is a bit large (140 mb more or less), could be a problem?

**Comment by gdmcbain** [comment] 2021-11-01 19:42
I don't think that size should be a problem.

The error message isn't very instructive but looking at the line in the code that raised it

https://github.com/nschloe/meshio/blob/8622ab2fdb261bc3aa6ddbc2f5bb0daa293f3be9/src/meshio/gmsh/main.py#L33-L34

I'd say that your `input.msh` is not a Gmsh MSH file. Quite a few unrelated formats use the .msh suffix. You might need to specify the input file format on the command line.

**Comment by ruffi92** [comment] 2021-11-02 08:10
I know that the mesh generation process has been handled with ANSYS workbench, starting from a CAD model. 
Which file format have to specify? Or where i can find this information?

**Comment by keurfonluu** [comment] 2021-11-02 08:13
Add the option `--input-format ansys` in your command.

**Comment by ruffi92** [comment] 2021-11-02 09:46
it worked!! thanks a lot for all the support! @keurfonluu @gdmcbain 
I obtain the following WARNING message, can skip these or i have to add some other option? 

> WARNING:root:Zone specification not supported yet ('wall', 'wall-core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'wall-core-porousupper'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-activefuel-core-upperfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-inlet-zone-core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-activefuel-core-lowerfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-lowerfuel-core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-porousupper-core-upperfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-lowerfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-inlet-zone'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-activefuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-upperfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('interior', 'interior-core-porousupper'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-lowerfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-inlet-zone'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-activefuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-upperfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('fluid', 'core-porousupper'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-lowerfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-inlet-zone'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-porous-lower'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-activefuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-upperfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'boundary-core-porousupper'). Skipping.
> WARNING:root:Zone specification not supported yet ('pressure-outlet', 'outlet'). Skipping.
> WARNING:root:Zone specification not supported yet ('velocity-inlet', 'inlet'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'lowerfuel'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'ringb'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'ringc'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'ringd'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'ringe'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'ringf'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'elements'). Skipping.
> WARNING:root:Zone specification not supported yet ('wall', 'upperfuel'). Skipping.

**Comment by gdmcbain** [comment] 2021-11-03 00:00
This new problem looks like a duplicate of #815.

**Comment by nschloe** [comment] 2021-11-11 17:02
See [here](https://stackoverflow.com/a/11029841/353337) on how to disable warnings.

**Closed by nschloe** 2021-11-11 17:02 UTC
