### ISSUE TITLE
Regression: Meshio doesn't recognize physical groups

### ISSUE THREAD

**Issue by cbcoutinho** [nschloe/meshio#169] opened 2017-12-20 00:59 UTC
I use gmsh physical groups pretty extensively, so it was a surprise to me when all of my tests started failing with an updated version of `meshio`.

Most of my testing code looks similar to the following, where I'm expected a tuple:
```python
points, cells, point_data, cell_data, field_data = meshio.read(my_msh_filename)
```

I noticed my tests were failing all of a sudden, most likely after a pip update. For now, I'm going to fix my code to 1.9.4. The following information may be relevant to you.

The mesh file, `test2D.msh`:
```msh
$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
5
1 1 "lower"
1 2 "right"
1 3 "upper"
1 4 "left"
2 5 "domain"
$EndPhysicalNames
$Nodes
9
1 0 0 0
2 1 0 0
3 1 1 0
4 0 1 0
5 0.499999999998694 0 0
6 1 0.499999999998694 0
7 0.5000000000020591 1 0
8 0 0.5000000000020591 0
9 0.5000000000003766 0.5000000000003766 0
$EndNodes
$Elements
12
1 1 2 1 1 1 5
2 1 2 1 1 5 2
3 1 2 2 2 2 6
4 1 2 2 2 6 3
5 1 2 3 3 3 7
6 1 2 3 3 7 4
7 1 2 4 4 4 8
8 1 2 4 4 8 1
9 3 2 5 1 1 5 9 8
10 3 2 5 1 8 9 7 4
11 3 2 5 1 5 2 6 9
12 3 2 5 1 9 6 3 7
$EndElements
```

My simple test script, `main.py`
```python
#!/usr/bin/env python3

import meshio

print(meshio.read('test2D.msh'))
```

Expected output, using `meshio==1.9.4`:
```python
(array([[ 0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.5,  0. ,  0. ],
       [ 1. ,  0.5,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0.5,  0.5,  0. ]]), {'line': array([[0, 4],
       [4, 1],
       [1, 5],
       [5, 2],
       [2, 6],
       [6, 3],
       [3, 7],
       [7, 0]]), 'quad': array([[0, 4, 8, 7],
       [7, 8, 6, 3],
       [4, 1, 5, 8],
       [8, 5, 2, 6]])}, {}, {'line': {'physical': array([1, 1, 2, 2, 3, 3, 4, 4]), 'geometrical': array([1, 1, 2, 2, 3, 3, 4, 4])}, 'quad': {'physical': array([5, 5, 5, 5]), 'geometrical': array([1, 1, 1, 1])}}, {'lower': 1, 'right': 2, 'upper': 3, 'left': 4, 'domain': 5})
```

After some quick tests, I noticed a changed in the output from 1.9.4 and 1.10.0-1.10.3, where it looks like additional output was added. I haven't had the time to go through the code yet, but my code fails on this output as well, due to multiple physical groups being found by meshio:
```python
(array([[ 0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.5,  0. ,  0. ],
       [ 1. ,  0.5,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0.5,  0.5,  0. ]]), {'line': array([[0, 4],
       [4, 1],
       [1, 5],
       [5, 2],
       [2, 6],
       [6, 3],
       [3, 7],
       [7, 0]]), 'quad': array([[0, 4, 8, 7],
       [7, 8, 6, 3],
       [4, 1, 5, 8],
       [8, 5, 2, 6]])}, {}, {'line': {'physical': array([1, 1, 2, 2, 3, 3, 4, 4]), 'geometrical': array([1, 1, 2, 2, 3, 3, 4, 4])}, 'quad': {'physical': array([5, 5, 5, 5]), 'geometrical': array([1, 1, 1, 1])}}, {'lower': array([1, 1]), 'right': array([2, 1]), 'upper': array([3, 1]), 'left': array([4, 1]), 'domain': array([5, 2])})
```

But then in versions 1.10.4 and later, the physical group data is lost. Incorrect output using latest `meshio==1.10.5`:
```python
(array([[ 0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.5,  0. ,  0. ],
       [ 1. ,  0.5,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0.5,  0.5,  0. ]]), {'line': array([[0, 4],
       [4, 1],
       [1, 5],
       [5, 2],
       [2, 6],
       [6, 3],
       [3, 7],
       [7, 0]]), 'quad': array([[0, 4, 8, 7],
       [7, 8, 6, 3],
       [4, 1, 5, 8],
       [8, 5, 2, 6]])}, {}, {'line': {}, 'quad': {}}, {'lower': array([1, 1]), 'right': array([2, 1]), 'upper': array([3, 1]), 'left': array([4, 1]), 'domain': array([5, 2])})
```

**Comment by nschloe** [comment] 2017-12-20 01:06
Yup, the physical field data fell prey to a fix in the gmsh i/o today. Everything below 1.10.5 should work for you. The issue is that gmsh's tags where taken as cell data so far when really `$ElementData` is what we should have been looking at all along. 1.10.5 fixes that.

The proper fix for this is to implement tags for meshio, perhaps with another output variable. Some data types support that (I can think of gmsh and exodus right now). At any rate, this is a substantial endeavor.

Perhaps I can think of a way for bringing back _reading_ of tag data into cell_data, but that code would be untested. I'll think about it.

**Comment by cbcoutinho** [comment] 2017-12-20 01:15
Alrighty gotcha, thanks for explanation. I was hoping this was at
least on your radar. It sounds like a pretty serious structural change
on the part of meshio, and I'm fine with the current functionality of
fixing my projects meshio version.

Thanks for your help

**Comment by gdmcbain** [comment] 2017-12-20 02:36
Ah.  This breaks my app too: it relied upon the `physical` entry of the `cell_data` dicts to encode 
* subdomains for discontinuous material properties
* mixed boundary conditions

so now throws `KeyError`.

I'm not sure that I follow the distinction between tags, `cell_data` and `$ElementData`.  While a tag is usually specified in advance (as in my two applications, above) and element data is more conventionally used for solution fields in finite-volume or discontinuous Galerkin methods, but still in the end aren't they just both mappings from the set of cells/elements to R or R^n?

Are 'cells' and 'elements' the same?

**Comment by nschloe** [comment] 2017-12-20 09:49
> I'm not sure that I follow the distinction between tags, cell_data and $ElementData.

There's cell (=element) data: Real or integer data connected to each cell of the grid. All mesh formats have that, in gmsh it's called `$ElementData`.

Then, there are cell groups: Either tagged (as in gmsh) or explicitly grouped together (as in Exodus). While integer cell data could be used for the same purpose, cell groups are most of the time used to describe different physical entities in a mesh.

Initially, I had overlooked that gmsh actually has `$ElementData`, so I had hijacked the tagging feature to at least support integer cell data.

**Comment by nschloe** [comment] 2017-12-20 10:16
Alright, should be fixed now. Get 1.10.6.

**Closed by nschloe** 2017-12-20 10:16 UTC

**Comment by gdmcbain** [comment] 2017-12-21 04:14
Thank you, yes, the effect of setting `geom.add_physical_point` etc in pygmsh is again preserved through `pygmsh.generate_mesh` which uses meshio internally.  I have my subdomains and boundary conditions back and my app works again.

Thanks for the explanation of `cell_data` and `ElementData`.  

That is interesting about the concept of 'cell group’: it could be represented as:
* a map from cells to something like an enum indexing the groups or 
* the other way around, as a list of groups, each entry being a list of indices of cells.  

The latter would be more useful for common finite element method operations like integrating over a subdomain or patch of boundary; I guess that's why Exodus provides them?  Rather than having to iterate over all cells, filter by inclusion in group, then operate.  At the moment (1.10.7) though, am I right in thinking that only the former is returned by `meshio.read`?  (In `cell_data[*]['physical']`?)  But perhaps worrying about this is premature optimization.

**Comment by nschloe** [comment] 2017-12-21 11:13
> The latter would be more useful for common finite element method operations

My thoughts exactly. Let's discuss this further at #175.
